name: Build pear

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: ["386", amd64, arm, arm64]
        goos: [windows, linux, darwin]
        exclude:
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: "386"
    name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Build for ${{ matrix.goarch }}
        env:
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
          CGO_ENABLED: "0"
        run: |
          go build -ldflags="-s -w" -o build/pear

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pear-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/pear
